@baseUrl = http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/posts/comments
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "comment": "This is Jane's first comment!",
  "postId": "63655d8d21f3afbd3d671945",
  "profilePicture": "https://res.cloudinary.com/deq8aqjgy/image/upload/v1667327427/636165c200f16260cb5165f8",
  "userTo": "636165c200f16260cb5165f8"
}

###
POST {{baseUrl}}/{{urlPath}}/posts/comments
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "comment": "This is Jane's second comment",
  "postId": "63655d8d21f3afbd3d671945",
  "profilePicture": "https://res.cloudinary.com/deq8aqjgy/image/upload/v1667327427/636165c200f16260cb5165f8",
  "userTo": "636165c200f16260cb5165f8"
}

###
POST {{baseUrl}}/{{urlPath}}/posts/comments
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "comment": "This is John's first comment!",
  "postId": "63655d8d21f3afbd3d671945",
  "profilePicture": "https://res.cloudinary.com/deq8aqjgy/image/upload/v1667327427/636165c200f16260cb5165f8",
  "userTo": "6367fecb86a9fc3f784363db"
}

###
GET {{baseUrl}}/{{urlPath}}/posts/comments/usernames/63655d8d21f3afbd3d671945
Content-Type: application/json
Accept: application/json
withCredentials: true


###
GET {{baseUrl}}/{{urlPath}}/posts/comments/63655d8d21f3afbd3d671945/6369000465b738ae88a8e5dc
Content-Type: application/json
Accept: application/json
withCredentials: true

